Ir para o conteúdo
Pesquise ou pule para…
Solicitação de pull s
questões
Mercado
Explorar
 
@Naftali21 
rafaballerini
/
rafaballerini
Público
Código
questões
7
Solicitações de pull
10
Ações
Projetos
Wiki
Segurança
Percepções
rafaballerini/.github/fluxos de trabalho/ cobrinha.yml
@rafaballerini
rafaballerini Atualização cobrinha.yml
Último commit d2470b3 on 29 May 2021
 História
 1 colaborador
26 linhas (22 sloc)  589 Bytes
   
nome : Gerar Dados

em :
  schedule : # executa a cada 12 horas
-cron     : " * */12 * * * "
  workflow_dispatch :

empregos :
  construir :
    name : Naftali21
    run-on : ubuntu-latest
    passos :
      # Animação de cobra
      - usa : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : Naftali21
          svg_out_path : dist/github-contribution-grid-snake.svg

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
  
© 2022 GitHub, Inc.
Termos
Privacidade
Segurança
Status
Documentos
Entre em contato com o GitHub
Preços
API
Treinamento
Blogue
Cerca de
Carregamento concluído
